"""empty message

Revision ID: 97525942b354
Revises: 9cba88ba95fd
Create Date: 2017-05-22 15:41:04.383486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97525942b354'
down_revision = '9cba88ba95fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('owners', sa.Column('username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'username')
    op.drop_column('owners', 'email')
    # ### end Alembic commands ###
